"""Add models_info column to Configuration model

Revision ID: 0581bedcc7c4
Revises: 2d3dc737db78
Create Date: 2024-10-29 02:29:45.285000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0581bedcc7c4'
down_revision = '2d3dc737db78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('models_info', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_column('models_info')
    # ### end Alembic commands ###
